name: Build

on:
  # 当推送到 main 分支时触发
  push:
    branches:
      - main
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 开启 SSH 服务 (Start SSH service)
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 15

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BetterGI
        path: ./publish
